# Generated by Django 3.2.8 on 2022-03-28 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klienci', '0004_umowa_umowa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zgloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temat', models.CharField(max_length=100)),
                ('tresc', models.TextField(blank=True, max_length=500)),
                ('dataUtworzenia', models.DateTimeField(auto_now_add=True)),
                ('statusRozwiazany', models.BooleanField(default=None)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klienci.klient')),
            ],
        ),
    ]
