# Generated by Django 3.2.8 on 2022-03-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_zgloszenieodpowiedzi'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgloszenie',
            name='zalacznik',
            field=models.FileField(blank=True, null=True, upload_to='helpdesk'),
        ),
        migrations.AddField(
            model_name='zgloszenieodpowiedzi',
            name='zalacznik',
            field=models.FileField(blank=True, null=True, upload_to='helpdesk'),
        ),
    ]
