# Generated by Django 3.2.8 on 2022-04-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_auto_20220331_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgloszenie',
            name='zamkniete',
            field=models.BooleanField(default=None),
        ),
    ]
