# Generated by Django 3.2.8 on 2022-04-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_remove_zgloszenie_zamkniete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgloszenie',
            name='statusRozwiazany',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
