# Generated by Django 3.2.8 on 2022-03-21 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zarzadzanie', '0003_auto_20220321_0235'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gmina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaGminy', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('pesel', models.CharField(max_length=11)),
                ('seriaDowodu', models.CharField(max_length=9)),
                ('aktywny', models.BooleanField(default=True)),
                ('numerGSM', models.CharField(blank=True, max_length=20, null=True)),
                ('numerStacjonarny', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('miastoZamieszkania', models.CharField(max_length=50)),
                ('ulicaZamieszkania', models.CharField(max_length=50)),
                ('numerZamieszkania', models.CharField(max_length=50)),
                ('numerMieszkaniaZamieszkania', models.CharField(blank=True, max_length=50, null=True)),
                ('kodPocztowyZamieszkania', models.CharField(max_length=6)),
                ('numerInstalacji', models.CharField(max_length=50)),
                ('numerMieszkaniaInstalacji', models.CharField(blank=True, max_length=50, null=True)),
                ('kodPocztowyInstalacji', models.CharField(max_length=6)),
                ('stanKonta', models.FloatField(default=0)),
                ('gminaInstalacji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klienci.gmina')),
            ],
        ),
        migrations.CreateModel(
            name='Miasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaMiasta', models.CharField(max_length=50)),
                ('gmina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klienci.gmina')),
            ],
        ),
        migrations.CreateModel(
            name='Wojewodztwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaWojewodztwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ulica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaUlicy', models.CharField(max_length=50)),
                ('miasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klienci.miasto')),
            ],
        ),
        migrations.CreateModel(
            name='Skan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaSkanu', models.CharField(max_length=50)),
                ('skan', models.FileField(blank=True, null=True, upload_to='skany')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klienci.klient')),
            ],
        ),
        migrations.CreateModel(
            name='Powiat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaPowiatu', models.CharField(max_length=50)),
                ('wojewodztwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klienci.wojewodztwo')),
            ],
        ),
        migrations.CreateModel(
            name='KontoBankowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerKonta', models.CharField(max_length=26)),
                ('klient', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='klienci.klient')),
            ],
        ),
        migrations.CreateModel(
            name='KlientHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('zmieniono', models.CharField(max_length=100)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klienci.klient')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='klient',
            name='miastoInstalacji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klienci.miasto'),
        ),
        migrations.AddField(
            model_name='klient',
            name='powiatInstalacji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klienci.powiat'),
        ),
        migrations.AddField(
            model_name='klient',
            name='taryfa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zarzadzanie.taryfa'),
        ),
        migrations.AddField(
            model_name='klient',
            name='ulicaInstalacji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klienci.ulica'),
        ),
        migrations.AddField(
            model_name='klient',
            name='uzytkownik',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='klient',
            name='wojewodztwoInstalacji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klienci.wojewodztwo'),
        ),
        migrations.AddField(
            model_name='gmina',
            name='powiat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klienci.powiat'),
        ),
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('typ', models.CharField(max_length=100)),
                ('koszt', models.FloatField()),
                ('saldoPo', models.FloatField()),
                ('faktura', models.FileField(blank=True, null=True, upload_to='')),
                ('dataWystawienia', models.DateField(blank=True)),
                ('terminPlatnosci', models.DateField(blank=True, null=True)),
                ('sposobPlatnosci', models.CharField(blank=True, max_length=100)),
                ('dataDodania', models.DateTimeField(auto_now_add=True)),
                ('notatka', models.TextField(blank=True, max_length=100)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klienci.klient')),
            ],
        ),
    ]
