# Generated by Django 3.2.8 on 2022-03-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarzadzanie', '0003_auto_20220321_0235'),
        ('klienci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='pakiety',
            field=models.ManyToManyField(blank=True, to='zarzadzanie.PakietDodatkowy'),
        ),
    ]
