# Generated by Django 3.2.8 on 2022-03-25 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klienci', '0002_klient_pakiety'),
    ]

    operations = [
        migrations.CreateModel(
            name='Umowa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('dataOd', models.DateField(blank=True)),
                ('dataDo', models.DateField(blank=True)),
                ('dataDodania', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klienci.klient')),
            ],
        ),
    ]
