# Generated by Django 3.2.8 on 2022-04-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klienci', '0004_umowa_umowa'),
    ]

    operations = [
        migrations.AddField(
            model_name='umowa',
            name='czyPodpisana',
            field=models.BooleanField(default=False),
        ),
    ]
