# Generated by Django 3.2.8 on 2022-04-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klienci', '0005_umowa_czypodpisana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='numerStacjonarny',
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
    ]
