# Generated by Django 3.2.8 on 2022-04-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klienci', '0010_alter_klient_numermieszkaniainstalacji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
