# Generated by Django 3.2.8 on 2022-03-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PakietDodatkowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaPakietu', models.CharField(max_length=100)),
                ('cena', models.FloatField()),
                ('podatek', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Taryfa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaTaryfy', models.CharField(max_length=100)),
                ('pobieranie', models.CharField(max_length=20)),
                ('wysylanie', models.CharField(max_length=20)),
                ('cena', models.FloatField()),
                ('podatek', models.FloatField()),
            ],
            options={
                'managed': True,
            },
        ),
    ]
