# Generated by Django 3.2.8 on 2022-03-21 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zarzadzanie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taryfa',
            name='podatek',
        ),
    ]
