# Generated by Django 3.2.8 on 2022-04-12 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zarzadzanie', '0004_uprawnieniagrup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uprawnieniagrup',
            old_name='modulZardzanie',
            new_name='modulZarzadzanie',
        ),
    ]
