# Generated by Django 3.2.8 on 2022-04-13 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zarzadzanie', '0005_rename_modulzardzanie_uprawnieniagrup_modulzarzadzanie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UprawnieniaGrup',
        ),
    ]
